name: "FAP: Build & Release (T-Union Master)"

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]   # 推送以 v 开头的 tag 时触发发布
  pull_request:
  workflow_dispatch:

permissions:
  contents: write     # 允许创建 Release、上传资产

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    name: "ufbt: Build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirement
        run: pip install -r requirements.txt
      - name: Build City and Line database
        run: python compile_database.py
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-hw-target: f7
          sdk-url: "https://github.com/Next-Flip/Momentum-Firmware/releases/download/mntm-010/flipper-z-f7-sdk-mntm-010.zip"
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          # See ufbt action docs for other output variables
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      # 仅在 tag push 时创建 Release 并附上 .fap
      - name: Create GitHub Release (tag pushes only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.build-app.outputs.fap-artifacts }}/*.fap
          generate_release_notes: true
